version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      minor-and-patch-updates:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
    automerge:
      enable: true
      types:
        - 'minor'
        - 'patch'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      minor-and-patch-actions:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
    automerge:
      enable: true
      types:
        - 'minor'
        - 'patch'
